---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    openshift.io/cluster-monitoring: "true"
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/part-of: developer-lightspeed-workshop
