---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - devspaces/namespace.yaml
  - devspaces/operatorgroup.yaml
  - devspaces/subscription.yaml
  - mta/namespace.yaml
  - mta/operatorgroup.yaml
  - mta/subscription.yaml
