---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/part-of: developer-lightspeed-workshop
    workshop.namespace-type: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: workshop-system
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/part-of: developer-lightspeed-workshop
    workshop.namespace-type: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/part-of: developer-lightspeed-workshop
    app.kubernetes.io/name: gitea
    workshop.namespace-type: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-application-controller
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
