---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etherpad
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: https://github.com/kamorisan/rhdl-workshop-provision.git
    targetRevision: main
    path: gitops/platform-instances/etherpad/chart
    helm:
      valueFiles:
        - ../../../config/etherpad-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: '*'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
